from pathlib import Path
base=Path('/mnt/data/tcc-v2')
header='''<header><div class="container head"><a class="brand" href="index.html"><img src="images/logo.png" alt="TCC – The Coffee Club"></a><div class="head-actions"><span class="label">MENU</span><button class="toggle" data-toggle aria-label="Open menu" aria-expanded="false"><span class="hamb"><i></i><i></i><i></i></span></button></div></div></header><div class="overlay" data-overlay></div><aside class="drawer"><div class="drawer-top"><img class="drawer-logo" src="images/logo.png" alt="TCC"><button class="close" data-close aria-label="Close">×</button></div><div class="eyebrow">The Coffee Club · Nellore</div><nav class="nav"><a href="index.html">Home <span>01</span></a><a href="about.html">About TCC <span>02</span></a><a href="menu.html">Menu <span>03</span></a><a href="gallery.html">Gallery <span>04</span></a><a href="visit.html">Visit Us <span>05</span></a><a href="contact.html">Contact <span>06</span></a></nav><div class="menu-call"><div class="eyebrow">Hungry yet?</div><h3>Explore the TCC menu.</h3><a class="btn gold" href="menu.html">Open Menu</a></div><div class="social"><a class="btn" href="tel:+919059059553">Call</a><a class="btn" href="https://wa.me/919059059553" target="_blank">WhatsApp</a><a class="btn" href="https://www.instagram.com/tcc_nellore" target="_blank">Instagram</a></div></aside>'''
bar='''<nav class="bar"><a href="tel:+919059059553">☎ Call</a><a class="accent" href="menu.html">☕ Menu</a><a href="https://maps.app.goo.gl/LTdYTXNZPJU4qetv6?g_st=ac" target="_blank">⌖ Map</a></nav>'''
footer='''<footer class="footer"><div class="container"><img src="images/logo.png" alt="TCC – The Coffee Club"><p><strong>TCC – THE COFFEE CLUB</strong></p><p>Good Coffee. Good Food. Good Vibes.</p><div class="footer-actions"><a class="btn light" href="tel:+919059059553">Call</a><a class="btn light" href="https://wa.me/919059059553" target="_blank">WhatsApp</a><a class="btn light" href="https://www.instagram.com/tcc_nellore" target="_blank">Instagram</a><a class="btn light" href="https://maps.app.goo.gl/LTdYTXNZPJU4qetv6?g_st=ac" target="_blank">Google Maps</a></div><p style="margin-top:25px">© <span data-year></span> TCC – The Coffee Club. All rights reserved.</p></div></footer>'''
def page(title,desc,body): return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#173c2b"><meta name="description" content="{desc}"><title>{title}</title><link rel="stylesheet" href="style.css"></head><body>{header}{body}{footer}{bar}<script src="script.js"></script></body></html>'''

home='''<main><section class="hero"><div class="container"><img class="hero-logo" src="images/logo.png" alt="TCC"><div class="eyebrow">The Coffee Club · Nellore</div><h1>Good Coffee.<br>Good Food.<br><span style="color:var(--gs)">Good Vibes.</span></h1><p>A premium coffee experience crafted for Nellore — made for slow mornings, good conversations and everyday moments.</p><div class="actions"><a class="btn gold" href="menu.html">Explore Menu</a><a class="btn light" href="visit.html">Visit TCC</a></div></div><div class="scroll">SCROLL TO EXPLORE ↓</div></section><section class="cream"><div class="container split"><div class="heading"><div class="eyebrow">Our Story</div><h2>A coffee club made for Nellore.</h2><p>TCC – The Coffee Club was created with a simple vision: bring a premium coffee experience to Nellore, with quality, flavour and creativity under one roof.</p><a class="btn dark" href="about.html">Discover TCC</a></div><div class="photo"><img src="images/space-2.jpg" alt="Inside TCC"></div></div></section><section><div class="container"><div class="heading center"><div class="eyebrow">The TCC Experience</div><h2>More than just coffee.</h2><p>Come for the cup. Stay for the vibe.</p></div><div class="features"><article class="feature"><div class="icon">☕</div><h3>Crafted Coffee</h3><p>Classic espresso favourites, signature cold brews and refreshing drinks.</p></article><article class="feature"><div class="icon">✨</div><h3>Good Vibes</h3><p>A warm, premium space for conversations, work or simply unwinding.</p></article><article class="feature"><div class="icon">🍽️</div><h3>Good Food</h3><p>A growing menu designed to pair naturally with your coffee and time at TCC.</p></article></div></div></section><section class="dark-section"><div class="container"><div class="heading center"><div class="eyebrow">Inside TCC</div><h2>Your corner of the city.</h2><p style="color:#d8dfd8">Take a look around before you walk in.</p></div><div class="gallery"><div class="big"><img src="images/space-1.jpg" alt="TCC interior"></div><img src="images/space-3.jpg" alt="TCC ambience"><img src="images/space-4.jpg" alt="TCC restaurant"></div><div class="gallery-caption"><span>Warm interiors. Coffee-club energy. Nellore.</span><a class="btn light" href="gallery.html">View Gallery</a></div></div></section><section><div class="container"><div class="visit"><div class="eyebrow">Come Say Hello</div><h2>Ready for your next coffee?</h2><p style="color:#d8dfd8;max-width:600px">Open every day, right opposite SRK School in Magunta Layout, Nellore.</p><div class="actions"><a class="btn gold" href="visit.html">Get Directions</a><a class="btn light" href="tel:+919059059553">Call TCC</a></div></div></div></section></main>'''

about='''<main><section class="pagehero"><div class="container"><div class="eyebrow">02 · Our Story</div><h1>About TCC</h1><p>A premium coffee experience, created for Nellore.</p></div></section><section class="cream"><div class="container split"><div class="card"><div class="eyebrow">The Idea</div><h2 style="font-size:38px">A place to pause, connect and enjoy.</h2><p>TCC – The Coffee Club was created with a simple vision — to bring a premium coffee experience to Nellore.</p><p>From carefully crafted coffees and signature cold brews to refreshing teas and delicious food, TCC brings together quality, flavour and creativity under one roof.</p><p>Whether you're starting your day with a perfect cup, catching up with friends, getting some work done, or simply looking for a place to unwind, TCC is made to be your everyday coffee club.</p><div class="signature">Good Coffee. Good Food. Good Vibes.</div></div><div class="photo"><img src="images/space-1.jpg" alt="TCC interior"></div></div></section><section><div class="container"><div class="heading center"><div class="eyebrow">What TCC Stands For</div><h2>Simple things, done well.</h2></div><div class="features"><article class="feature"><div class="icon">01</div><h3>Quality</h3><p>Thoughtful ingredients, carefully prepared drinks and a focus on consistency.</p></article><article class="feature"><div class="icon">02</div><h3>Comfort</h3><p>A welcoming space where you can stay for a quick coffee or settle in.</p></article><article class="feature"><div class="icon">03</div><h3>Community</h3><p>A coffee club built around conversations, connections and everyday moments.</p></article></div></div></section></main>'''

gallery='''<main><section class="pagehero"><div class="container"><div class="eyebrow">04 · Inside TCC</div><h1>The Space</h1><p>Warm corners, premium details and a relaxed coffee-club atmosphere.</p></div></section><section><div class="container"><div class="gallery"><div class="big"><img src="images/space-1.jpg" alt="TCC interior"></div><img src="images/space-2.jpg" alt="TCC cafe"><img src="images/space-3.jpg" alt="TCC ambience"></div><div style="margin-top:10px"><img style="width:100%;height:360px;object-fit:cover;border-radius:17px" src="images/space-4.jpg" alt="TCC restaurant"></div></div></section></main>'''

visit='''<main><section class="pagehero"><div class="container"><div class="eyebrow">05 · Find Us</div><h1>Visit TCC</h1><p>Come in, grab a cup and make yourself comfortable.</p></div></section><section class="cream"><div class="container"><div class="visit"><div class="eyebrow">The Coffee Club · Nellore</div><h2>Your table is waiting.</h2><div class="info"><div><small>Address</small><strong>Opposite SRK School, Magunta Layout, Nellore, Andhra Pradesh – 524003</strong></div><div><small>Opening Hours</small><strong>Every day · 7:00 AM – 11:30 PM</strong></div><div><small>Phone</small><strong>90590 59553</strong></div><div><small>WhatsApp</small><strong>90590 59553</strong></div></div><div class="actions"><a class="btn gold" href="https://maps.app.goo.gl/LTdYTXNZPJU4qetv6?g_st=ac" target="_blank">Open Google Maps</a><a class="btn light" href="tel:+919059059553">Call TCC</a><a class="btn light" href="https://wa.me/919059059553" target="_blank">WhatsApp</a></div></div></div></section></main>'''

contact='''<main><section class="pagehero"><div class="container"><div class="eyebrow">06 · Say Hello</div><h1>Contact TCC</h1><p>Questions, reservations or just want to say hi? Reach us directly.</p></div></section><section><div class="container"><div class="contact-grid"><article class="contact-card"><div class="eyebrow">Call</div><h3>Speak to us</h3><p>For quick questions or anything you need before visiting.</p><a class="btn dark" href="tel:+919059059553">Call 90590 59553</a></article><article class="contact-card"><div class="eyebrow">WhatsApp</div><h3>Message TCC</h3><p>Send us a WhatsApp message for a quick conversation.</p><a class="btn dark" href="https://wa.me/919059059553" target="_blank">Open WhatsApp</a></article><article class="contact-card"><div class="eyebrow">Instagram</div><h3>Follow the vibe</h3><p>See TCC updates, photos and what's happening at the cafe.</p><a class="btn dark" href="https://www.instagram.com/tcc_nellore" target="_blank">Open Instagram</a></article><article class="contact-card"><div class="eyebrow">Location</div><h3>Find us in Nellore</h3><p>Opposite SRK School, Magunta Layout, Nellore, Andhra Pradesh – 524003.</p><a class="btn dark" href="https://maps.app.goo.gl/LTdYTXNZPJU4qetv6?g_st=ac" target="_blank">Get Directions</a></article></div></div></section></main>'''

items=[('Espresso','₹99'),('Long Black','₹190'),('Latte','₹249'),('Mocha','₹249'),('Spanish Latte','₹299'),('Cortado','₹315'),('Hot Chocolate','₹349'),('Affogato','₹349'),('Iced Americano','₹245'),('Iced Latte','₹290'),('Iced Mocha','₹320'),('Classic Cold Coffee','₹275'),('Spanish Iced Latte','₹320'),('Classic Cold Brew','₹350'),('Coco Brew','₹350'),('Monte Bianco','₹350'),('Apple Pie Latte','₹280'),('Biscotti Latte','₹280'),('Orange Espresso','₹320'),('Pineapple Float','₹360'),('Peach Iced Tea','₹200'),('Lemon Iced Tea','₹200'),('Berry Iced Tea','₹200'),('Traditional Chai','₹35'),('South Indian Coffee','₹40'),('Masala Bun','₹99')]
coffee=''.join(f'<div class="item"><h3>{n}</h3><span class="price">{p}</span></div>' for n,p in items[:20])
refresh=''.join(f'<div class="item"><h3>{n}</h3><span class="price">{p}</span></div>' for n,p in items[20:])
menu=f'''<main><section class="pagehero"><div class="container"><div class="eyebrow">03 · A Taste of TCC</div><h1>Our Menu</h1><p>Explore the current TCC drinks selection. The complete food menu will be added once the final menu is ready.</p></div></section><section><div class="container"><div class="menu-note"><strong>Menu update:</strong> This is the current V1 drinks selection. The final confirmed food menu will replace this temporary list.</div><h2 class="menu-title">Coffee & Favourites</h2><div class="menu-grid">{coffee}</div><h2 class="menu-title">Iced, Tea & Refreshing</h2><div class="menu-grid">{refresh}</div><div style="text-align:center;margin-top:35px"><a class="btn dark" href="index.html">Back to TCC</a></div></div></section></main>'''

pages={'index.html':('TCC – The Coffee Club | Nellore','Premium coffee experience in Nellore.',home),'about.html':('About TCC | The Coffee Club Nellore','The story behind TCC.',about),'gallery.html':('Gallery | TCC – The Coffee Club Nellore','Explore the TCC space.',gallery),'visit.html':('Visit TCC | The Coffee Club Nellore','Find TCC in Magunta Layout, Nellore.',visit),'contact.html':('Contact TCC | The Coffee Club Nellore','Contact TCC by phone, WhatsApp or Instagram.',contact),'menu.html':('Menu | TCC – The Coffee Club Nellore','Explore the current TCC drinks menu.',menu)}
for fn,(title,desc,body) in pages.items(): (base/fn).write_text(page(title,desc,body),encoding='utf-8')
